name: Rust

on:
  push:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Format Devices
        run: |
          cd device
          for package in $(ls -d usb*); do
            echo Format $package
            (cd $package && cargo fmt --check)
          done
      - name: Format Rust Host
        run: |
          cd host/usb-bulk-rust
          cargo fmt --check
      - name: Build Devices
        run: |
          cd device
          for package in $(ls -d usb*); do
            echo Build $package
            (cd $package && cargo build)
          done
      - name: Build Rust Host
        run: |
          cd host/usb-bulk-rust
          cargo build
      - name: Clippy Devices
        run: |
          cd device
          echo Clippy $package
          for package in $(ls -d usb*); do
            (cd $package && cargo clippy -- --Dwarnings)
          done
      - name: Clippy Rust Host
        run: |
          cd host/usb-bulk-rust
          cargo clippy -- -Dwarnings
